=== ptesser/scherma-castelfranco/data/articoli.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.articoli.com"
			targetNamespace="http://www.articoli.com" elementFormDefault="qualified">

<xs:element name="testi" type="tipo-testo"/>

<xs:complexType name="tipo-testo">
	<xs:sequence minOccurs="0" maxOccurs="unbounded">
		<xs:element name="articolo" minOccurs="0" maxOccurs="unbounded" type="tipo-articolo" /> <!-- inserire in un tag <div> -->
	</xs:sequence>
</xs:complexType>

<xs:complexType name="tipo-articolo">
	<xs:sequence>
			<xs:element name="luogo" type="xs:string" /> <!-- inserire in un tag <p> -->
			<xs:element name="data" type="xs:date" /> <!-- inserire in un tag <p> -->
			<xs:element name="titolo" type="tipo-titolo" />
			<xs:element name="img" nillable="true" type="tipo-immagine" /> <!-- da inserire nel src del tag img -->
			<xs:element name="paragrafo" type="tipo-paragrafo" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="tipo-titolo" mixed="true">
	<xs:choice minOccurs="0" maxOccurs="unbounded">
		<xs:element name="span" type="tipo-span" />
		<xs:element name="abbr" type="tipo-abbr"/>
	</xs:choice>
</xs:complexType>

<xs:complexType name="tipo-immagine">
	<xs:attribute name="src" type="xs:anyURI"  />
	<xs:attribute name="alt" type="xs:string"  />
</xs:complexType>

<xs:complexType name="tipo-paragrafo" mixed="true"> <!-- alternanza tra testo ed elementi span-->
	<xs:choice minOccurs="0" maxOccurs="unbounded">
		<xs:element name="span" type="tipo-span" />
		<xs:element name="em" type="xs:string" />
		<xs:element name="strong" type="xs:string" />
		<xs:element name="abbr" type="tipo-abbr"/>
	</xs:choice>
</xs:complexType>

<xs:complexType name="tipo-span" >  <!--Content model con attributi e contenuto semplice -->
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="lang" type="xs:string" default="en" />
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<xs:complexType name="tipo-abbr" >  <!--Content model con attributi e contenuto semplice -->
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="title" type="xs:string" use="required"/>
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>



</xs:schema>

=== ptesser/scherma-castelfranco/data/articoli.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="articoli.xsl" ?>

<ts:testi xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.articoli.com" xs:schemaLocation="http://www.articoli.com articoli.xsd"  xmlns:ts="http://www.articoli.com">
	<articolo>
		<luogo>Udine</luogo>
		<data>2014-02-08</data>
		<titolo>AI CAMPIONATI ITALIANI CADETTI E GIOVANI 2014 LA SCHERMA CASTELFRANCO VENETO E’ PROTAGONISTA ASSOLUTA NELLA SPADA FEMMINILE PRIMA CON ELEONORA DE MARCHI (CLASSE ’98) VICECAMPIONESSA ITALIANA E BEATRICE CAGNIN (CLASSE ’99) MEDAGLIA DI BRONZO NELLA CATEGORIA TRIENNALE DELLE CADETTE!</titolo>
		<img src="../img/gare/udine-08.02.2014.jpg" alt="L'immagine mostra le due atlete premiate"/>
		<paragrafo>Nei giorni 7, 8 e 9 Febbraio si sono svolti al Palaindoor di Udine i Campionati Italiani Cadetti e Giovani (<span lang="en">Under</span>-17 e <span lang="en">Under</span>-20) per le specialità del Fioretto, della Sciabola e della Spada. In questa competizione, alla quale ci si doveva qualificare in base a due prove di accesso, hanno potuto prendere parte i primi trentasei atleti – per arma - della classifica nazionale generale, pertanto già essersi qualificati rappresentava un buon traguardo! Di tutti gli<abbr title="Under">U</abbr>-17 ed <abbr title="Under">U</abbr>-20 del Circolo Scherma Castelfranco Veneto A.S.D. che hanno tentato di arrivare a questo primo traguardo gli unici ad esservi riusciti sono stati: Beatrice Cagnin, Eleonora De Marchi e Ludovica Favarotto (la prima classe ’99 e pertanto al primo anno di militanza in questa fascia; le altre due sue compagne di sala entrambe classe 1998!) sia come Cadette che come Giovani (nelle Cadette il Circolo Scherma Castelfranco Veneto è stata l’unica società – assieme alle Polizia di Stato di Roma – ad avere tre atlete nelle prime trentasei in Italia; addirittura nelle Giovani la prima assoluta sempre con le stesse bravissime tre spadiste!); Lorenzo Lucidi e Riccardo Macchion invece si erano qualificati per la gara Giovani <span lang="en">Under</span>-20. Ma vediamo come si è dipanata la giornata di gara. Alle 11,45 hanno preso il via i sei gironi da sei tiratrici che avrebbero determinato le prime trentadue spadiste che sarebbero entrate nella seconda e decisiva fase della gara: l’Eliminazione Diretta. Solita partenza “a razzo” per De Marchi che – nonostante una sconfitta a quattro – entrava in Diretta col dorsale numero quattro; con due sconfitte ed aliquota quasi uguale troviamo la Cagnin e la Favarotto rispettivamente ottava e nona! Prima vittima della giornata è stata la “sfortunata” Favarotto che con la Pistoiese Irene Biagioni - dopo una bellissima rimonta – sul quattordici pari, ha visto la sua punta schizzare via dal bersaglio avversario e con lei la possibilità di raggiungere la zona podio. Sempre più confortanti segnali arrivano comunque dalla nostra teutonica spadista castellana! Le nostre altre due atlete continuavano invece la loro marcia trionfale con una serie di incontri da manuale, che permettevano ad entrambe di arrivare in semifinale. Qui, a causa dell’abbinamento che deriva dall’inizio dell’Eliminazione Diretta, le due spadiste si sono dovute affrontare proprio in semifinale per giocarsi l’accesso alla finalissima, e qui la maggiore determinazione ed esperienza della De Marchi le hanno fatto avere la meglio sulla compagna di sala che si è vista stoppare sul comunque buonissimo terzo scalino del podio col punteggio di 10-15. Nella finalissima contro la forte torinese dell’Isef Alessandra Bozza la De Marchi – dopo un inizio al fulmicotone che aveva inebetito l’avversaria – si è vista pian piano rintuzzare il gap ottenuto nella prima parte di incontro, e anche complice un “dubbio” arbitraggio – da tutti, esperti e non,  sottolineato – la comunque eccellente Eleonora De marchi si fermava sul secondo gradino del podio col risicato punteggio di 13-15. A tenere compagnia alla Cagnin sul terzo gradino invece c’era la forlivese Sara Billi, sconfitta in semifinale proprio dalla Bozza. Il giorno seguente i primi a salire sulle pedane del bel Palaindoor di Udine sono stati i Giovani (<span lang="en">Under</span>-20) della Spada Maschile. I nostri due portacolori erano Lorenzo Lucidi (presente malgrado una brutta forma influenzale lo abbia fermato per tutta la settimana prima della gara precludendogli così la possibilità di allenarsi al meglio!) e Riccardo Macchion. Ottima la partenza di Macchion che, con quattro vittorie ed una sconfitta a 4 nel Girone di qualificazione, entrava in Diretta come numero quattro assoluto! Meno bene Lucidi che faticava a “far girare” le gambe e non riusciva pertanto a far altro che vincere un incontro ma – per differenza stoccate – era l’ultimo degli spadisti in gara che acquisiva il diritto di poter accedere all’Eliminazione Diretta. Qui, come si può ben comprendere, il suo primo incontro è stato contro un atleta molto più alto di lui nella classifica che ha eliminato il nostro comunque lodevole schermidore con relativa facilità. Altra storia invece per Macchion che nei sedicesimi riusciva ad avere la meglio sul genovese delle Pompilio Jacopo Musso col punteggio di 15-12; negli ottavi di finale incappava purtroppo in uno dei probabili finalisti, il ferrarese Villani, che fermava il nostro bravo Riccardo nel tabellone degli ottavi di finale consentendogli in ogni caso di raggiungere una lodevole nona posizione assoluta nel ranking nazionale <span lang="en">Under</span>-20! Nel primo pomeriggio, nella gara destinata alle Giovani <span lang="en">Under</span>-20 di Spada femminile si ripresentavano le nostre tre inossidabili Beatrice Cagnin, Eleonora De Marchi e Ludovica Favarotto tutte e tre pronte a voler bissare e, se del caso, anche migliorare la già buonissima performance del giorno prima! Dopo il consueto Girone all’Italiana a cinque stoccate per determinare la classifica individuale di accesso alla fase dell’Eliminazione Diretta la De Marchi, con tutte vittorie accedeva a questo secondo Tabellone come numero tre assoluto; la Cagnin, con tre vittorie e due sconfitte aveva il dorsale tredici, mentre la Favarotto con due vittorie e tre sconfitte il numero venticinque. Nell’Eliminazione Diretta la prima a cadere è stata la Favarotto nei sedicesimi di finale, ad opera della bergamasca Baroli. Cagnin e De Marchi invece continuavano la loro marcia verso le zone alte della classifica approdando entrambe nei quarti di finale: qui la prima riusciva ad avere la meglio della fortissima azzurrina <span lang="en">Under</span>-20 Roberta Marzani della Bergamasca Creberg solo alla priorità dopo un incontro tiratissimo fino all’ultimo secondo (9-8 il punteggio in favore della castellana); la De Marchi – probabilmente anche un po’ troppo affaticata dagli incontri precedenti, sommati all’entusiasmante prestazione del giorno prima! – partiva molto bene contro la forte torinese Bozza, che però, durante i tre tempi dell’assalto, riusciva a recuperare e fermare la nostra sempre brava Eleonora nei quarti di finale. La Cagnin invece, ringalluzzita dal bel <span lang="en">match</span> contro la Marzani, andava in semifinale a scontrarsi contro la ventenne siciliana Giulia Signorelli e la lasciava “per strada” con l’eloquente <span lang="en">score</span> di 15-6 salendo così in pedana per l’ultimo importantissimo incontro di questa sua seconda giornata di gare contro uno dei “mostri sacri” dell’attuale panorama nazionale ed anche internazionale della spada femminile <span lang="en">Under</span>-20: la sicula – in forza alle fiamme Oro Roma – Alberta Santuccio, reduce da una strepitosa vittoria in Coppa del Mondo <span lang="en">Under</span>-20 solo alcuni giorni prima. La nostra giovanissima spadista (classe ‘99) ha cercato con tutti i suoi mezzi di opporre una marcata resistenza agli attacchi dell’avversaria, ma la troppa esperienza legata anche ad una superiore “fisicità” della Santuccio non hanno permesso alla Cagnin molto, lasciando a Beatrice solo la soddisfazione di aver impegnato per tutta la durata dei tre tempi la brava avversaria. La comprova è il punteggio di 13-9 con cui è terminato l’assalto! A corollario di questi due giorni di vare va ricordato che il Circolo Scherma Castelfranco Veneto nella categoria Giovani di Spada Femminile è risultata la prima Società asoluta in Italia come numero di iscritte a questa gara (tre spadoste fra le prime trentasei nella classifica Nazionale <span lang="en">Under</span>-20), e la prima a pari merito con le Fiamme Oro Roma nella gara del giorno precedente, sempre con le stesse tre bravissime schermitrici!!! Complimenti da tutti!
		</paragrafo>
	</articolo>

	<articolo>
		<luogo>Chiavari (GE)</luogo>
		<data>2014-02-04</data>
		<titolo>ECCELLENTI NOTIZIE AI GIOCHI DEL MEDITERRANEO <span lang="en">UNDER</span> 17 E <span lang="en">UNDER</span> 20 L’INDOMITA BEATRICE CAGNIN NELLE CADETTE <abbr title="Under">U</abbr>-17 SPADA CONQUISTA UN’OTTIMA MEDAGLIA D’ARGENTO ED E’ ANCHE L’UNICA ITALIANA A SALIRE SUL PODIO!
		</titolo>
		<img src="../img/gare/chiavari-25.01.2014.jpg" alt="le quattro atlete premiate"/>
